### ISSUE TITLE
Trying to run lighthouse against a host that is in another container

### ISSUE THREAD

**Issue by abbad** [justinribeiro/dockerfiles#41]
First, thank you for making this docker image. 

When I am trying to run lighthouse(from your container) against my localhost(which is in another container), it gives me an error that the connection is refused. 

This is the command that I am running inside the docker container. 
```
lighthouse --chrome-flags="--headless --disable-gpu" http://localhost:8000
```
Now I installed lighthouse cli on my machine. And I tested it against my localhost. It works as expected and it is giving me the results back. 

Was wondering if you encountered this error before.  

Also, I am using your image via a docker-compose file 

```
version: '3'

services:
    lighthouse:
        image: justinribeiro/lighthouse
        volumes:
            - .:/home/chrome/reports
        cap_add:
            - SYS_ADMIN
        ports:
            - "8000:8000"
```

Let me know if you need more clarification on this issue.
